driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  name: inspec
  format: doc

platforms:
  - name: centos-5.11
  - name: centos-6.7
  - name: centos-7.2
  - name: debian-7.10
    run_list: apt::default
  - name: debian-8.4
    run_list: apt::default
  - name: fedora-23
    run_list: yum::dnf_yum_compat
  - name: ubuntu-12.04
    run_list: apt::default
  - name: ubuntu-14.04
    run_list: apt::default
  - name: ubuntu-16.04
    run_list: apt::default

suites:
- name: client
  run_list:
    - recipe[ossec::client]
  data_bags_path: 'test/fixtures/data_bags'
- name: server
  run_list:
    - recipe[ossec::server]
  data_bags_path: 'test/fixtures/data_bags'
- name: agent_auth
  run_list:
    - recipe[ossec::agent_auth]
  attributes:
    ossec:
      agent_server_ip: 10.0.2.2
- name: authd
  run_list:
    - recipe[ossec::authd]
  driver_config:
    network:
    - ['forwarded_port', { guest: 1514, host: 1514, protocol: 'udp' }]
    - ['forwarded_port', { guest: 1515, host: 1515, protocol: 'tcp' }]
  includes:
    - centos-7.2
    - debian-8.4
